package com.network.projet.ussd.model.entities;

import com.network.projet.ussd.model.enums.UserType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;

/**
 * User entity representing a user in the USSD system.
 * This is the base entity for all user types (Client, Freelance, Agency, Delivery Person).
 * 
 * <p>Maps to the 'user' table in PostgreSQL database.
 * Uses R2DBC for reactive database access.
 * 
 * <p>Inheritance Strategy: Single table with discriminator column 'role'.
 * 
 * @author Thomas Djotio Ndié
 * @version 1.0
 * @since 2025-01-15
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table("user")
public class User {
    
    /**
     * Unique identifier for the user.
     * Auto-generated by database sequence.
     */
    @Id
    private Long id;
    
    /**
     * User role type (CLIENT, FREELANCE, AGENCY, DELIVERY_PERSON).
     * Acts as discriminator for inheritance.
     */
    @Column("role")
    private UserType role;
    
    /**
     * Full name of the user.
     * Required field, max length 120 characters.
     */
    @Column("name")
    private String name;
    
    /**
     * Phone number in international format.
     * Unique constraint, used for USSD identification.
     * Example: +237600000000
     */
    @Column("phone")
    private String phone;
    
    /**
     * Email address (optional).
     * Unique constraint if provided.
     */
    @Column("email")
    private String email;
    
    /**
     * Hashed password for authentication.
     * Never store plain text passwords.
     */
    @Column("password")
    private String password;
    
    /**
     * Account creation timestamp.
     * Automatically set by database.
     */
    @Column("created_at")
    private LocalDateTime created_at;
    
    /**
     * Checks if user is a client.
     * 
     * @return true if user type is CLIENT
     */
    public boolean isClient() {
        return UserType.CLIENT.equals(this.role);
    }
    
    /**
     * Checks if user is a delivery person.
     * 
     * @return true if user type is DELIVERY_PERSON or FREELANCE
     */
    public boolean isDeliveryPerson() {
        return UserType.DELIVERY_PERSON.equals(this.role) 
            || UserType.FREELANCE.equals(this.role);
    }
    
    /**
     * Checks if user is an agency.
     * 
     * @return true if user type is AGENCY
     */
    public boolean isAgency() {
        return UserType.AGENCY.equals(this.role);
    }
    
    /**
     * Gets masked phone number for display (last 4 digits visible).
     * 
     * @return masked phone number (e.g., +237****0000)
     */
    public String getMaskedPhone() {
        if (phone == null || phone.length() < 8) {
            return phone;
        }
        
        int visible_digits = 4;
        int mask_length = phone.length() - visible_digits;
        String mask = "*".repeat(mask_length);
        String visible_part = phone.substring(mask_length);
        
        return mask + visible_part;
    }
}